#!/bin/bash

# DisputeHub Quick Deploy Script
# This guides you through deploying to Vercel + connecting GoDaddy domain

clear

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║              DISPUTEHUB → DISPUTE-HUB.COM                      ║"
echo "║                  Quick Deploy Guide                            ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "This script will guide you through deploying DisputeHub."
echo ""
read -p "Press ENTER to continue..."
echo ""

# Step 1
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Login to Vercel"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Running: npx vercel login"
echo ""
npx vercel login

if [ $? -ne 0 ]; then
  echo ""
  echo "❌ Login failed. Please try again manually:"
  echo "   npx vercel login"
  exit 1
fi

echo ""
echo "✅ Logged in successfully!"
echo ""
read -p "Press ENTER to continue to deployment..."
echo ""

# Step 2
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Deploy to Vercel (Preview)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This will create a preview deployment."
echo ""
echo "When prompted:"
echo "  - Project name: disputehub"
echo "  - Settings correct?: Yes"
echo ""
read -p "Press ENTER to start deployment..."
echo ""
npx vercel

echo ""
echo "✅ Preview deployment complete!"
echo ""

# Step 3
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Add Environment Variables"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "You need to add 23 environment variables in Vercel dashboard."
echo ""
echo "📋 See full list in: ENV_VARS_CHECKLIST.md"
echo ""
echo "Do this now:"
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Click your 'disputehub' project"
echo "3. Settings → Environment Variables"
echo "4. Add all 23 variables from your .env file"
echo ""
echo "⚠️  IMPORTANT: Use PRODUCTION values for:"
echo "   - DATABASE_URL (production database)"
echo "   - STRIPE_SECRET_KEY (live mode, not test)"
echo "   - NEXT_PUBLIC_APP_URL = https://dispute-hub.com"
echo ""
read -p "Press ENTER when you've added all environment variables..."
echo ""

# Step 4
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Deploy to Production"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This will deploy to production with your environment variables."
echo ""
read -p "Press ENTER to deploy to production..."
echo ""
npx vercel --prod

echo ""
echo "✅ Production deployment complete!"
echo ""

# Step 5
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 5: Add Domain in Vercel"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Click your 'disputehub' project"
echo "3. Settings → Domains"
echo "4. Add domain: dispute-hub.com"
echo "5. Add domain: www.dispute-hub.com"
echo ""
echo "Vercel will show you DNS records to add in GoDaddy."
echo ""
read -p "Press ENTER when you've added the domains in Vercel..."
echo ""

# Step 6
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 6: Configure GoDaddy DNS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Login to GoDaddy.com"
echo "2. My Products → dispute-hub.com → Manage DNS"
echo "3. Add these records (use values from Vercel):"
echo ""
echo "   Record 1:"
echo "   Type: A"
echo "   Name: @"
echo "   Value: 76.76.21.21 (or IP from Vercel)"
echo ""
echo "   Record 2:"
echo "   Type: CNAME"
echo "   Name: www"
echo "   Value: cname.vercel-dns.com"
echo ""
echo "4. Save changes"
echo ""
read -p "Press ENTER when DNS is configured..."
echo ""

# Step 7
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 7: Update Clerk"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://clerk.com/dashboard"
echo "2. Select your DisputeHub app"
echo "3. Configure → Domains"
echo "4. Add: https://dispute-hub.com"
echo "5. Add: https://www.dispute-hub.com"
echo ""
read -p "Press ENTER when Clerk is configured..."
echo ""

# Done!
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    DEPLOYMENT COMPLETE! 🎉                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Your site is now deploying to:"
echo "  🌐 https://dispute-hub.com"
echo "  🌐 https://www.dispute-hub.com"
echo ""
echo "⏳ DNS propagation takes 5-60 minutes."
echo ""
echo "Test your site:"
echo "  curl -I https://dispute-hub.com"
echo ""
echo "Or visit in browser:"
echo "  open https://dispute-hub.com"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 Monitor your deployment:"
echo "  - Vercel Dashboard: https://vercel.com/dashboard"
echo "  - View logs: npx vercel logs"
echo "  - Check domains: npx vercel domains ls"
echo ""
echo "🎯 DisputeHub is now LIVE! 🚀"
echo ""
